-- -- lazy.nvim plugin setup
return{}
--   "nvimtools/none-ls.nvim",
--   config = function()
--     local null_ls = require("null-ls")
--
--     null_ls.setup({
--       sources = {
--         null_ls.builtins.formatting.black,
--         null_ls.builtins.formatting.isort,
--       },
--     })
--
--     -- Format on save
--     vim.api.nvim_create_autocmd("BufWritePre", {
--       pattern = "*.py",
--       callback = function()
--         vim.lsp.buf.format({ async = false })
--       end,
--     })
--   end,
-- }
