[general]
  import = ["tokyo-night.toml", "keybinds.toml"]

[window]
  opacity = 0.6

[font]
  normal = {family = "JetBrainsMono Nerd Font" }
  size = 14
  glyph_offset={x=0, y=0} 

[cursor]
  style = {shape="Block", blinking="on"}

[terminal]
  shell = {program="/bin/zsh"}
